name: "Second action"
on:
  workflow_run:
    workflows: ["First action"]
    types: [completed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: first-action.yml
          name: original-refs
          workflow_conclusion: success
      - name: set REF_BASE to env
        run: |
          echo "BASE=$(cat base.txt)" >> $GITHUB_ENV
          echo "CURRENT_BRANCH=$(cat current-branch.txt)" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.CURRENT_BRANCH }}
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ env.BASE }}
          filters: |
            src:
              - src/**
            lib:
              - lib/**
      - name: check
        run: |
          echo '${{ toJSON(steps.filter.outputs) }}'
